//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BewareTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag_task
    {
        public int task_id { get; set; }
        public int tag_id { get; set; }
        public int tag_taskID { get; set; }
    
        public virtual tag tag { get; set; }
        public virtual task task { get; set; }
    }
}
